import Head from 'next/head';
import Image from 'next/image';

import HomeComponent from '../components/Home/HomeComponent';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Out My Closet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComponent />


    </div>
  )
}
